version: '3'
services:
  web-client:
    restart: on-failure
    build:
      context: .
      dockerfile: applications/web-client/Dockerfile
    image: docker.pkg.github.com/maxjoehnk/remote-party-games/web-client:latest
  matchmaking:
    restart: on-failure
    build:
      context: .
      dockerfile: applications/matchmaking/Dockerfile
    image: docker.pkg.github.com/maxjoehnk/remote-party-games/matchmaking:latest
    volumes:
      - ./game_assets:/src/applications/matchmaking/assets
  image:
    restart: on-failure
    build:
      context: .
      dockerfile: applications/image/Dockerfile
    image: docker.pkg.github.com/maxjoehnk/remote-party-games/image:latest
    environment:
      MATCHMAKING_URL: http://matchmaking:8090
    volumes:
      - images:/etc/party-games/storage
  proxy:
    restart: on-failure
    build: applications/proxy
    depends_on:
      - web-client
      - matchmaking
    image: docker.pkg.github.com/maxjoehnk/remote-party-games/proxy:latest
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"
      traefik.http.routers.party-games-proxy.rule: "Host(`${DOMAIN-party.maxjoehnk.me`)"
      traefik.http.services.party-games-proxy.loadbalancer.server.port: "80"
      traefik.docker.network: "web"
volumes:
  images:

networks:
  web:
    external:
      name: web
