version: '3'
services:
    web-client:
        restart: on-failure
        build: applications/web-client
        image: party-games/web-client:latest
    matchmaking:
        restart: on-failure
        build: applications/matchmaking
        image: party-games/matchmaking:latest
    image:
        restart: on-failure
        build: applications/image
        image: party-games/image:latest
    proxy:
        restart: on-failure
        build: applications/proxy
        depends_on:
          - web-client
          - matchmaking
        image: party-games/proxy:latest
        networks:
          - web
          - default
        labels:
          traefik.enable: "true"
          traefik.http.routers.party-games-proxy.rule: "Host(`party.maxjoehnk.me`)"
          traefik.http.services.party-games-proxy.loadbalancer.server.port: "80"
          traefik.docker.network: "web"

